# Query for DDoS network analytics metrics from Cloudflare Analytics API
query DosdNetworkAnalytics(
  $accountId: String!
  $datetimeGeq: String!
  $datetimeLeq: String!
) {
  viewer {
    accounts(filter: { accountTag: $accountId }) {
      dosdNetworkAnalyticsAdaptiveGroups(
        filter: {
          datetime_geq: $datetimeGeq
          datetime_leq: $datetimeLeq
        }
        limit: 1000
      ) {
        sum {          
          bits
          packets
        }
      }
    }
  }
}
